# .streamlit/secrets.toml
fb_access_token = "EAAZAml1ODEHwBOZCrjYE1z0ICJO7zYZCfTfSLuCTsW4HWUyTA0W1nySI3MFmhU039YKFzQ1ucBoiDb6Bnde2vWkXBbxqEZBVeZAmtjHRyWiXi0whobaFwatlkRfxAo7IP7DXIxNzEjF3sqQSagtZCbrTPHymyP0ZBGGKtK9vctO8ZBFXwOyKIWyZCI6iZBvXqZBCSypISJ67l3ZA"
ad_account_id = "act_730706002767475"
